# Generated by Django 6.0.3 on 2026-04-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('active', '実行中'), ('archived', '終了')], default='draft', max_length=10),
        ),
    ]
