# Generated by Django 6.0.3 on 2026-04-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitlog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habit',
            name='count_type',
            field=models.CharField(blank=True, choices=[('week', '週'), ('month', '月')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('daily', '毎日'), ('interval', '〇日おき'), ('weekday', '曜日指定'), ('count', '回数指定')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='habit',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='weekdays',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'date'], name='habits_habi_habit_i_e7faa4_idx'),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_log'),
        ),
    ]
