# Generated by Django 6.0.3 on 2026-05-08 01:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habitlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitlog',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
