# Generated by Django 6.0.3 on 2026-05-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habitskip'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_run_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
