# Generated by Django 6.0.3 on 2026-05-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habit_next_run_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='next_run_date',
        ),
    ]
