# Generated by Django 6.0.3 on 2026-05-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_remove_habit_next_run_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitskip',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='habitskip',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_skip'),
        ),
    ]
