# Generated by Django 6.0.3 on 2026-06-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habitskip_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='count_type',
            field=models.CharField(blank=True, choices=[('week', '週'), ('month', '月')], default='week', max_length=10, null=True),
        ),
    ]
