# Generated by Django 6.0.3 on 2026-06-06 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_alter_habit_count_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitskip',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='habits.habit'),
        ),
        migrations.CreateModel(
            name='HabitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', '予定'), ('completed', '実施'), ('skipped', 'スキップ'), ('missed', '未実施')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='habits.habit')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['habit', 'date'], name='habits_habi_habit_i_4c5f8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_schedule')],
            },
        ),
    ]
