# Generated by Django 6.0.3 on 2026-06-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_habitskip_habit_habitschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitschedule',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='habitschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', '予定'), ('completed', '実施'), ('skipped', 'スキップ')], default='scheduled', max_length=20),
        ),
    ]
