# Generated by Django 6.0.3 on 2026-06-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_habitschedule_note_alter_habitschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(choices=[('#ef4444', 'レッド'), ('#f97316', 'オレンジ'), ('#eab308', 'イエロー'), ('#22c55e', 'グリーン'), ('#3b82f6', 'ブルー'), ('#a855f7', 'パープル'), ('#64748b', 'グレー')], default='#3b82f6', max_length=7),
        ),
    ]
