# Generated by Django 6.0.3 on 2026-04-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_delete_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(choices=[("draft", "下書き"), ("todo", "未着手"), ("doing", "進行中"), ("done", "完了")], default="draft", max_length=10),
        ),
    ]
