# Generated by Django 6.0.3 on 2026-06-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
